# backend/app/routes/generate.py
"""
SSE generation routes for DocHub.

POST /generate/prd
    Streams 7 PRD sections sequentially as SSE events.
    Each section is generated by a separate instructor/Anthropic call.
    Heartbeat events are emitted before every blocking call to prevent
    Railway proxy idle-timeout (30 s default).

POST /generate/stories
    3-step internal pipeline, all streamed as SSE events:
      Step 1 — CapabilityList extraction (single instructor call)
      Step 2 — SlicePlan with max 7 vertical slices (single instructor call)
      Step 3 — One UserStoryModel per slice (N instructor calls, N <= 7)

SSE format: `data: {JSON}\n\n`
Heartbeat:  `data: {"heartbeat": true}\n\n`
Terminal:   `data: {"done": true, ...}\n\n`

Routes contain zero business logic — all AI, RAG, DB, and workflow operations
are delegated to service layer functions imported from app.services.*.
"""

from __future__ import annotations

import asyncio
import json
import re
import time
from datetime import date
from typing import Annotated, AsyncGenerator, Optional

import structlog
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from sqlmodel import Session, select

from app.database import engine, get_session
from app.models import PRDMetadata, Project, UserStory
from app.services.story_diff import classify_stories
from app.services.ai import (
    AudienceSection,
    CapabilityList,
    DescriptionSection,
    OpenQuestionsSection,
    ProblemSection,
    SlicePlan,
    SuccessSection,
    TitleSection,
    UserStoryModel,
    WhySection,
    generate_section,
)
from app.services.rag import HybridRetriever, save_prd_to_kb
from app.services.vector_store import get_chroma_client, get_or_create_collection
from app.services.versions import (
    EMBEDDING_MODEL,
    GENERATOR_MODEL,
    PRD_PROMPT_VERSION,
)
from app.services.workflow import WorkflowStatus, advance_status

logger = structlog.get_logger()

router = APIRouter()


# ---------------------------------------------------------------------------
# Request bodies
# ---------------------------------------------------------------------------


class GeneratePRDRequest(BaseModel):
    project_id: str


class GenerateStoriesRequest(BaseModel):
    project_id: str


# ---------------------------------------------------------------------------
# Hallucination detection helper
# ---------------------------------------------------------------------------

_NUMBER_RE = re.compile(r"\b\d+(?:[.,]\d+)?%?\b")


def _detect_hallucinations(prd_text: str, transcript_text: str) -> int:
    """
    Regex-based hallucination counter.

    Finds all numeric claims (integers, decimals, percentages) in the generated
    PRD and checks how many of them appear anywhere in the original transcript.
    Returns the count of numbers/percentages present in the PRD but absent from
    the transcript — these are potential hallucinations.

    The check is deliberately loose (substring match) to minimise false positives.
    LLM-as-judge is deferred — this is a fast heuristic only.
    """
    prd_numbers = set(_NUMBER_RE.findall(prd_text))
    if not prd_numbers:
        return 0
    missing = 0
    for num in prd_numbers:
        if num not in transcript_text:
            missing += 1
    return missing


# ---------------------------------------------------------------------------
# SSE helper
# ---------------------------------------------------------------------------


def _sse(payload: dict) -> str:
    """Serialise a dict to a well-formed SSE data line."""
    return f"data: {json.dumps(payload)}\n\n"


_HEARTBEAT = 'data: {"heartbeat": true}\n\n'


# ---------------------------------------------------------------------------
# POST /generate/prd
# ---------------------------------------------------------------------------


@router.post("/prd")
async def generate_prd(
    body: GeneratePRDRequest,
    db: Annotated[Session, Depends(get_session)],
) -> StreamingResponse:
    """
    Stream 7 PRD sections as Server-Sent Events.

    The generator function is defined inline and closed over `body` and `db`
    so that the route handler itself stays thin.  The StreamingResponse wraps
    the async generator and sets the correct Content-Type header.
    """
    # Validate project exists and is in the correct state before opening the
    # stream.  A 4xx response before StreamingResponse starts is still a
    # normal JSON error — once StreamingResponse starts, errors must be sent
    # as SSE events instead.
    statement = select(Project).where(Project.id == body.project_id)
    project: Optional[Project] = db.exec(statement).first()

    if project is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Project '{body.project_id}' not found.",
        )

    # Allow re-generation from PRD_GENERATED (user saved answers and wants a refresh).
    _allowed_for_prd = {WorkflowStatus.TRANSCRIPT_UPLOADED, WorkflowStatus.PRD_GENERATED}
    if project.status not in _allowed_for_prd:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=(
                f"PRD generation requires status TRANSCRIPT_UPLOADED or PRD_GENERATED; "
                f"current status is '{project.status.value}'."
            ),
        )

    # Load saved Q&A answers to inject into section prompts
    qa_answers: dict = {}
    if project.qa_answers:
        try:
            qa_answers = json.loads(project.qa_answers)
        except json.JSONDecodeError:
            qa_answers = {}

    is_regeneration = project.status == WorkflowStatus.PRD_GENERATED
    transcript_text: str = project.transcript_text or ""
    project_id: str = project.id
    project_name: str = project.name

    return StreamingResponse(
        _prd_stream(project_id, project_name, transcript_text, qa_answers=qa_answers, is_regeneration=is_regeneration),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",  # disable Nginx buffering on Railway
        },
    )


async def _prd_stream(
    project_id: str,
    project_name: str,
    transcript_text: str,
    qa_answers: Optional[dict] = None,
    is_regeneration: bool = False,
) -> AsyncGenerator[str, None]:
    """
    Async generator that drives the 7-section PRD generation pipeline.

    Owns its own SQLModel Session (opened via `with Session(engine)`) so that
    FastAPI's dependency cleanup cannot close the session mid-stream.

    Execution order:
    1. RAG retrieval (transcript[:500] as query).
    2. 7 sequential section calls, each preceded by a heartbeat.
    3. Save prd_json + advance_status + KB indexing.
    4. PRDMetadata row written to SQLite after successful KB indexing.
    5. Hallucination check + pipeline_complete log event.
    6. Terminal {"done": true} SSE event.

    source_doc_ids are extracted from RAG node metadata (not generated by LLM).
    HybridRetriever.retrieve() and save_prd_to_kb() are synchronous — both are
    offloaded to a threadpool via asyncio.to_thread() to avoid blocking the
    event loop.
    """
    pipeline_start = time.monotonic()
    total_input_tokens = 0
    total_output_tokens = 0
    sections_with_retries: list[str] = []

    # ------------------------------------------------------------------
    # Step 1 — RAG retrieval (sync — offloaded to threadpool)
    # ------------------------------------------------------------------
    chroma_client = get_chroma_client()
    collection = get_or_create_collection(chroma_client)
    retriever = HybridRetriever(collection, top_k=5)

    # Use first 500 chars of transcript as retrieval query.
    # HybridRetriever.retrieve() is synchronous (calls openai.OpenAI() sync client)
    # so we offload to a threadpool to avoid blocking the event loop.
    rag_query = transcript_text[:500]
    retrieved_nodes = await asyncio.to_thread(
        retriever.retrieve,
        rag_query,
        5,           # top_k positional arg
        project_id,  # project_id positional arg
    )

    # Build doc_ids list from node metadata — assigned to sections, not by LLM
    source_doc_ids: list[str] = list({
        str(nws.node.metadata.get("doc_id", ""))
        for nws in retrieved_nodes
        if nws.node.metadata.get("doc_id")
    })

    # Build RAG context string for injection into prompts
    rag_context_parts: list[str] = []
    for nws in retrieved_nodes:
        meta = nws.node.metadata
        doc_id = meta.get("doc_id", "unknown")
        section = meta.get("section", "")
        text = nws.node.get_content()
        rag_context_parts.append(f"[Source: {doc_id} / {section}]\n{text}")
    rag_context = "\n\n---\n\n".join(rag_context_parts) if rag_context_parts else "(No prior knowledge base context available for this product area.)"

    # Build Q&A context from saved PM answers (injected into every section prompt
    # so the LLM can close gaps and respect conflict decisions throughout the PRD).
    qa_context = ""
    if qa_answers:
        qa_lines: list[str] = []
        for key, answer in qa_answers.items():
            if not answer or not answer.strip():
                continue
            if key.startswith("gap:"):
                q = key[4:]
                qa_lines.append(f"Gap question: {q}\nPM answer: {answer.strip()}")
            elif key.startswith("conflict:"):
                c = key[9:]
                qa_lines.append(f"Conflict with '{c}' — PM decision: {answer.strip()}")
        if qa_lines:
            qa_context = (
                "PM HAS PROVIDED THE FOLLOWING ANSWERS TO PREVIOUS OPEN QUESTIONS.\n"
                "Use these answers to resolve ambiguities and close gaps in the PRD:\n\n"
                + "\n\n".join(qa_lines)
            )

    # ------------------------------------------------------------------
    # Step 2 — Generate 7 sections sequentially
    # ------------------------------------------------------------------

    # Running context of already-generated sections (injected into subsequent prompts)
    generated_sections: dict[str, str] = {}

    def _sections_so_far() -> str:
        if not generated_sections:
            return "(No sections generated yet.)"
        return "\n\n".join(
            f"### {k.upper()}\n{v}" for k, v in generated_sections.items()
        )

    # --- Section 1: Title ---
    yield _HEARTBEAT
    system_title = (
        "You are a senior product manager writing a Product Requirements Document (PRD). "
        "Your task is to write the PROJECT TITLE section.\n\n"
        "Rules:\n"
        "- The title must clearly describe the product or feature from the transcript.\n"
        "- Include an optional subtitle if the transcript provides enough context.\n"
        "- Ground every claim in the transcript. Mark anything inferred as '(inferred)'.\n"
        "- Do NOT invent features or capabilities not present in the transcript."
    )
    user_title = (
        f"TRANSCRIPT:\n{transcript_text}\n\n"
        f"KNOWLEDGE BASE CONTEXT (prior PRDs):\n{rag_context}\n\n"
        + (f"{qa_context}\n\n" if qa_context else "")
        + "Write the Title section."
    )

    try:
        title_result, inp, out = await generate_section(
            section_name="title",
            section_model=TitleSection,
            system_prompt=system_title,
            user_prompt=user_title,
            project_id=project_id,
        )
        total_input_tokens += inp
        total_output_tokens += out
    except Exception as exc:
        yield _sse({"error": f"Title section generation failed: {exc}", "done": True})
        return

    generated_sections["title"] = f"{title_result.title}" + (
        f" — {title_result.subtitle}" if title_result.subtitle else ""
    )
    section_dict = title_result.model_dump()
    yield _sse({"section": "title", "data": section_dict, "done": False})

    # --- Section 2: Description ---
    yield _HEARTBEAT
    system_description = (
        "You are a senior product manager writing a PRD. "
        "Your task is to write the DESCRIPTION section.\n\n"
        "Rules:\n"
        "- Write a high-level overview of the product or feature.\n"
        "- Reference related prior PRDs from the KB context where relevant.\n"
        "- Ground every claim in the transcript. Mark anything inferred as '(inferred)'.\n"
        "- Do NOT invent features or capabilities not present in the transcript."
    )
    user_description = (
        f"TRANSCRIPT:\n{transcript_text}\n\n"
        f"KNOWLEDGE BASE CONTEXT (prior PRDs):\n{rag_context}\n\n"
        f"SECTIONS GENERATED SO FAR:\n{_sections_so_far()}\n\n"
        + (f"{qa_context}\n\n" if qa_context else "")
        + "Write the Description section."
    )

    try:
        desc_result, inp, out = await generate_section(
            section_name="description",
            section_model=DescriptionSection,
            system_prompt=system_description,
            user_prompt=user_description,
            project_id=project_id,
        )
        total_input_tokens += inp
        total_output_tokens += out
    except Exception as exc:
        yield _sse({"error": f"Description section generation failed: {exc}", "done": True})
        return

    desc_result.source_doc_ids = source_doc_ids
    generated_sections["description"] = desc_result.overview
    section_dict = desc_result.model_dump()
    yield _sse({"section": "description", "data": section_dict, "done": False})

    # --- Section 3: Problem ---
    yield _HEARTBEAT
    system_problem = (
        "You are a senior product manager writing a PRD. "
        "Your task is to write the PROBLEM STATEMENT section.\n\n"
        "Rules:\n"
        "- State the core problem this product/feature solves.\n"
        "- List specific pain points raised in the transcript as bullet items.\n"
        "- Ground every claim in the transcript. Mark anything inferred as '(inferred)'.\n"
        "- Do NOT invent pain points not evidenced in the transcript."
    )
    user_problem = (
        f"TRANSCRIPT:\n{transcript_text}\n\n"
        f"KNOWLEDGE BASE CONTEXT (prior PRDs):\n{rag_context}\n\n"
        f"SECTIONS GENERATED SO FAR:\n{_sections_so_far()}\n\n"
        + (f"{qa_context}\n\n" if qa_context else "")
        + "Write the Problem Statement section."
    )

    try:
        problem_result, inp, out = await generate_section(
            section_name="problem",
            section_model=ProblemSection,
            system_prompt=system_problem,
            user_prompt=user_problem,
            project_id=project_id,
        )
        total_input_tokens += inp
        total_output_tokens += out
    except Exception as exc:
        yield _sse({"error": f"Problem section generation failed: {exc}", "done": True})
        return

    problem_result.source_doc_ids = source_doc_ids
    generated_sections["problem"] = (
        problem_result.problem_statement + "\n" + "\n".join(f"- {p}" for p in problem_result.pain_points)
    )
    section_dict = problem_result.model_dump()
    yield _sse({"section": "problem", "data": section_dict, "done": False})

    # --- Section 4: Why ---
    yield _HEARTBEAT
    system_why = (
        "You are a senior product manager writing a PRD. "
        "Your task is to write the WHY section (rationale and business value).\n\n"
        "Rules:\n"
        "- Explain WHY this product/feature must be built now.\n"
        "- Articulate the business value and strategic rationale.\n"
        "- Reference prior KB PRDs where there is strategic alignment or overlap.\n"
        "- Ground every claim in the transcript. Mark anything inferred as '(inferred)'.\n"
        "- Do NOT invent strategic rationale not evidenced in the transcript."
    )
    user_why = (
        f"TRANSCRIPT:\n{transcript_text}\n\n"
        f"KNOWLEDGE BASE CONTEXT (prior PRDs):\n{rag_context}\n\n"
        f"SECTIONS GENERATED SO FAR:\n{_sections_so_far()}\n\n"
        + (f"{qa_context}\n\n" if qa_context else "")
        + "Write the Why section."
    )

    try:
        why_result, inp, out = await generate_section(
            section_name="why",
            section_model=WhySection,
            system_prompt=system_why,
            user_prompt=user_why,
            project_id=project_id,
        )
        total_input_tokens += inp
        total_output_tokens += out
    except Exception as exc:
        yield _sse({"error": f"Why section generation failed: {exc}", "done": True})
        return

    why_result.source_doc_ids = source_doc_ids
    generated_sections["why"] = why_result.rationale + "\n" + why_result.business_value
    section_dict = why_result.model_dump()
    yield _sse({"section": "why", "data": section_dict, "done": False})

    # --- Section 5: Success ---
    yield _HEARTBEAT
    system_success = (
        "You are a senior product manager writing a PRD. "
        "Your task is to write the SUCCESS METRICS section.\n\n"
        "Rules:\n"
        "- List measurable success metrics (e.g. conversion rate, error rate, latency).\n"
        "- List specific KPIs with quantitative targets where the transcript provides them.\n"
        "- Ground every metric in the transcript. Mark anything inferred as '(inferred)'.\n"
        "- Do NOT invent numeric targets not mentioned in the transcript."
    )
    user_success = (
        f"TRANSCRIPT:\n{transcript_text}\n\n"
        f"KNOWLEDGE BASE CONTEXT (prior PRDs):\n{rag_context}\n\n"
        f"SECTIONS GENERATED SO FAR:\n{_sections_so_far()}\n\n"
        + (f"{qa_context}\n\n" if qa_context else "")
        + "Write the Success Metrics section."
    )

    try:
        success_result, inp, out = await generate_section(
            section_name="success",
            section_model=SuccessSection,
            system_prompt=system_success,
            user_prompt=user_success,
            project_id=project_id,
        )
        total_input_tokens += inp
        total_output_tokens += out
    except Exception as exc:
        yield _sse({"error": f"Success section generation failed: {exc}", "done": True})
        return

    success_result.source_doc_ids = source_doc_ids
    generated_sections["success"] = (
        "\n".join(f"- {m}" for m in success_result.metrics)
        + "\n"
        + "\n".join(f"- {k}" for k in success_result.kpis)
    )
    section_dict = success_result.model_dump()
    yield _sse({"section": "success", "data": section_dict, "done": False})

    # --- Section 6: Audience ---
    yield _HEARTBEAT
    system_audience = (
        "You are a senior product manager writing a PRD. "
        "Your task is to write the TARGET AUDIENCE section.\n\n"
        "Rules:\n"
        "- Identify the primary audience (the main user persona).\n"
        "- Identify secondary audiences if the transcript mentions them.\n"
        "- Include brief persona descriptions where the transcript provides them.\n"
        "- Ground every claim in the transcript. Mark anything inferred as '(inferred)'.\n"
        "- Do NOT invent personas not mentioned in the transcript."
    )
    user_audience = (
        f"TRANSCRIPT:\n{transcript_text}\n\n"
        f"KNOWLEDGE BASE CONTEXT (prior PRDs):\n{rag_context}\n\n"
        f"SECTIONS GENERATED SO FAR:\n{_sections_so_far()}\n\n"
        + (f"{qa_context}\n\n" if qa_context else "")
        + "Write the Target Audience section."
    )

    try:
        audience_result, inp, out = await generate_section(
            section_name="audience",
            section_model=AudienceSection,
            system_prompt=system_audience,
            user_prompt=user_audience,
            project_id=project_id,
        )
        total_input_tokens += inp
        total_output_tokens += out
    except Exception as exc:
        yield _sse({"error": f"Audience section generation failed: {exc}", "done": True})
        return

    audience_result.source_doc_ids = source_doc_ids
    generated_sections["audience"] = (
        audience_result.primary_audience
        + ("\n" + audience_result.secondary_audience if audience_result.secondary_audience else "")
    )
    section_dict = audience_result.model_dump()
    yield _sse({"section": "audience", "data": section_dict, "done": False})

    # --- Section 7: Open Questions / Risks ---
    yield _HEARTBEAT
    system_open_questions = (
        "You are a senior product manager writing a PRD. "
        "Your task is to write the OPEN QUESTIONS & RISKS section.\n\n"
        "This section has TWO required subsections — NEVER omit either:\n\n"
        "TYPE 1 — KB Conflicts (structured ConflictEntry objects):\n"
        "  Examine each knowledge base chunk provided. Identify direct contradictions between\n"
        "  what the transcript proposes and what existing PRDs state. For each conflict:\n"
        "    - source_prd_id: the doc_id from the KB chunk (e.g. 'payments-2024-01-15')\n"
        "    - conflicting_statement: quote the conflicting claim from the KB\n"
        "    - proposed_change: what the transcript proposes instead\n"
        "    - severity: 'blocking' | 'needs_discussion' | 'minor'\n"
        "    - kb_excerpt: copy verbatim the 1-3 sentences from the KB chunk that show the conflict.\n"
        "      Use the exact text from the [Source: ...] sections provided above.\n"
        "  If there are no conflicts, return an empty list — do NOT hallucinate conflicts.\n\n"
        "TYPE 2 — Transcript Gaps (GapEntry objects):\n"
        "  List questions about ambiguities, missing details, or decisions the transcript\n"
        "  left unresolved (e.g. scope boundaries, technical approach, compliance requirements).\n"
        "  For each gap:\n"
        "    - question: the gap as a clear, answerable question\n"
        "    - transcript_excerpt: copy 1-2 verbatim sentences from the TRANSCRIPT that prompted\n"
        "      this question (the statement that reveals the gap or ambiguity). If the gap\n"
        "      comes from complete absence of information, use an empty string.\n\n"
        "Ground every conflict in the KB context. Mark anything inferred as '(inferred)'."
    )
    user_open_questions = (
        f"TRANSCRIPT:\n{transcript_text}\n\n"
        f"KNOWLEDGE BASE CONTEXT (prior PRDs — check these for Type 1 conflicts):\n{rag_context}\n\n"
        f"SECTIONS GENERATED SO FAR:\n{_sections_so_far()}\n\n"
        + (f"{qa_context}\n\nIMPORTANT: For any gap or conflict where the PM has already provided an answer above, do NOT list it as an open question — it has been resolved. Only list gaps and conflicts that are still unanswered.\n\n" if qa_context else "")
        + "Write the Open Questions & Risks section. Include both Type 1 conflicts and Type 2 gaps."
    )

    try:
        oq_result, inp, out = await generate_section(
            section_name="open_questions",
            section_model=OpenQuestionsSection,
            system_prompt=system_open_questions,
            user_prompt=user_open_questions,
            project_id=project_id,
        )
        total_input_tokens += inp
        total_output_tokens += out
    except Exception as exc:
        yield _sse({"error": f"Open Questions section generation failed: {exc}", "done": True})
        return

    oq_result.source_doc_ids = source_doc_ids
    generated_sections["open_questions"] = (
        "\n".join(f"[CONFLICT] {c.conflicting_statement}" for c in oq_result.type1_conflicts)
        + "\n"
        + "\n".join(f"[GAP] {g.question}" for g in oq_result.type2_gaps)
    )
    section_dict = oq_result.model_dump()
    yield _sse({"section": "open_questions", "data": section_dict, "done": False})

    # ------------------------------------------------------------------
    # Step 3 — Persist PRD + advance workflow + index to KB
    # ------------------------------------------------------------------

    # Compose the full PRD text for hallucination detection
    full_prd_text = " ".join(generated_sections.values())
    hallucination_count = _detect_hallucinations(full_prd_text, transcript_text)

    # Build prd_json payload (store full section dicts, not the flattened text)
    prd_sections_payload: dict = {
        "title": title_result.model_dump(),
        "description": desc_result.model_dump(),
        "problem": problem_result.model_dump(),
        "why": why_result.model_dump(),
        "success": success_result.model_dump(),
        "audience": audience_result.model_dump(),
        "open_questions": oq_result.model_dump(),
    }
    prd_json_str = json.dumps(prd_sections_payload)

    # All DB operations use the generator-owned session.
    # Errors that require yielding SSE are captured as strings and yielded
    # OUTSIDE the `with` block so the session is not held open across a yield.
    _prd_persist_error: Optional[str] = None
    _prd_advance_error: Optional[str] = None

    with Session(engine) as db:
        # Persist prd_json on the Project row
        statement = select(Project).where(Project.id == project_id)
        project: Optional[Project] = db.exec(statement).first()
        if project is None:
            _prd_persist_error = "Project disappeared during generation."
        else:
            project.prd_json = prd_json_str
            db.add(project)
            db.commit()

            # Advance workflow status: TRANSCRIPT_UPLOADED → PRD_GENERATED.
            # On re-generation (is_regeneration=True) the project is already at
            # PRD_GENERATED — just overwrite prd_json in-place, no state advance needed.
            if not is_regeneration:
                try:
                    advance_status(project_id, WorkflowStatus.TRANSCRIPT_UPLOADED, db)
                except HTTPException as exc:
                    _prd_advance_error = exc.detail

        # Index PRD to ChromaDB knowledge base (sync — offloaded to threadpool).
        # Only run if project was found and status advanced successfully.
        if _prd_persist_error is None and _prd_advance_error is None:
            # product_area is derived from the title — normalise to lowercase slug.
            product_area = title_result.title.lower().replace(" ", "_").replace("/", "_")[:64]
            # Build flat section text dict for KB indexing (save_prd_to_kb expects dict[str, str])
            prd_sections_for_kb: dict[str, str] = {k: v for k, v in generated_sections.items()}

            kb_index_succeeded = False
            try:
                await asyncio.to_thread(
                    save_prd_to_kb,
                    prd_sections_for_kb,
                    project_id,
                    product_area,
                    collection,
                )
                kb_index_succeeded = True
            except RuntimeError as exc:
                # KB indexing failure is non-fatal — log and continue
                logger.warning(
                    "generate.prd.kb_index_failed",
                    project_id=project_id,
                    error=str(exc),
                )

            # Persist PRDMetadata row after successful KB indexing (Fix 4).
            # Skipped when KB indexing failed — no metadata to record.
            if kb_index_succeeded:
                prd_meta = PRDMetadata(
                    project_id=project_id,
                    product_area=product_area,
                    doc_id=f"{product_area}-{date.today().isoformat()}",
                    date=date.today().isoformat(),
                    status="active",
                    embedding_model=EMBEDDING_MODEL,
                )
                db.add(prd_meta)
                db.commit()

    # Yield any deferred SSE errors now that the session is closed.
    if _prd_persist_error is not None:
        yield _sse({"error": _prd_persist_error, "done": True})
        return
    if _prd_advance_error is not None:
        yield _sse({"error": f"Workflow advance failed: {_prd_advance_error}", "done": True})
        return

    # ------------------------------------------------------------------
    # Step 4 — Observability: pipeline_complete log event
    # ------------------------------------------------------------------
    total_latency_ms = (time.monotonic() - pipeline_start) * 1000

    logger.info(
        "pipeline_complete",
        project_id=project_id,
        generator_model=GENERATOR_MODEL,
        prompt_version=PRD_PROMPT_VERSION,
        embedding_model=EMBEDDING_MODEL,
        total_input_tokens=total_input_tokens,
        total_output_tokens=total_output_tokens,
        total_latency_ms=round(total_latency_ms, 2),
        sections_with_retries=sections_with_retries,
        hallucination_warnings=hallucination_count,
    )

    yield _sse({"done": True, "hallucination_count": hallucination_count})


# ---------------------------------------------------------------------------
# POST /generate/stories
# ---------------------------------------------------------------------------


@router.post("/stories")
async def generate_stories(
    body: GenerateStoriesRequest,
    db: Annotated[Session, Depends(get_session)],
) -> StreamingResponse:
    """
    Stream user story generation as Server-Sent Events (3-step pipeline).

    Validates project status before opening the stream; returns 4xx on error
    (before StreamingResponse starts, normal JSON error responses are still possible).
    """
    statement = select(Project).where(Project.id == body.project_id)
    project: Optional[Project] = db.exec(statement).first()

    if project is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Project '{body.project_id}' not found.",
        )

    # Allow re-generation from STORIES_GENERATED (produces a diff against existing rows).
    _allowed_for_stories = {WorkflowStatus.PRD_APPROVED, WorkflowStatus.STORIES_GENERATED}
    if project.status not in _allowed_for_stories:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=(
                f"Story generation requires status PRD_APPROVED or STORIES_GENERATED; "
                f"current status is '{project.status.value}'."
            ),
        )

    if not project.prd_json:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Project has no PRD content. Generate and approve the PRD first.",
        )

    prd_data: dict
    try:
        prd_data = json.loads(project.prd_json)
    except json.JSONDecodeError as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Stored prd_json is corrupted: {exc}",
        ) from exc

    project_id = project.id

    # Load existing stories for diff comparison on re-generation.
    existing_stories: list[UserStory] = list(
        db.exec(select(UserStory).where(UserStory.project_id == project_id)).all()
    )

    return StreamingResponse(
        _stories_stream(project_id, prd_data, existing_stories),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )


async def _stories_stream(
    project_id: str,
    prd_data: dict,
    existing_stories: "list[UserStory] | None" = None,
) -> AsyncGenerator[str, None]:
    """
    Async generator for the 3-step user story pipeline.

    Owns its own SQLModel Session (opened via `with Session(engine)`) so that
    FastAPI's dependency cleanup cannot close the session mid-stream.

    Step 1: Extract CapabilityList from PRD content (non-streamed, emits status event).
    Step 2: Generate SlicePlan (max 7 vertical slices).
    Step 3: Generate one UserStoryModel per slice, save each to DB immediately.

    All UserStory rows are saved inside the generator so partial results are
    durable if the connection drops after some stories are streamed.
    """
    # Build a compact PRD summary for the capability extraction prompt
    prd_summary = _flatten_prd_for_prompts(prd_data)

    # ------------------------------------------------------------------
    # Step 1 — Extract capabilities
    # ------------------------------------------------------------------
    yield _sse({"step": "extracting_capabilities"})
    yield _HEARTBEAT

    system_capabilities = (
        "You are a senior product manager. Extract a list of DISTINCT PRODUCT CAPABILITIES "
        "from the PRD provided. Each capability is a concrete function the product must perform "
        "(e.g. 'User can reset password via email link'). Be exhaustive but not redundant."
    )
    user_capabilities = f"PRD CONTENT:\n{prd_summary}\n\nExtract all product capabilities."

    try:
        capability_result, _, _ = await generate_section(
            section_name="capabilities",
            section_model=CapabilityList,
            system_prompt=system_capabilities,
            user_prompt=user_capabilities,
            project_id=project_id,
        )
    except Exception as exc:
        yield _sse({"error": f"Capability extraction failed: {exc}", "done": True})
        return

    capabilities_text = "\n".join(f"- {c}" for c in capability_result.capabilities)

    # ------------------------------------------------------------------
    # Step 2 — Generate vertical slices (max 7)
    # ------------------------------------------------------------------
    yield _HEARTBEAT

    system_slices = (
        "You are a senior product manager. Given a list of product capabilities, define "
        "VERTICAL SLICES for user story generation. Each slice is a thin, end-to-end user "
        "interaction that delivers independent value (no horizontal/technical-layer slices). "
        "Return AT MOST 7 slices. Prioritise by business value descending."
    )
    user_slices = (
        f"CAPABILITIES:\n{capabilities_text}\n\n"
        "Define vertical slices for user story generation. Maximum 7 slices."
    )

    try:
        slice_result, _, _ = await generate_section(
            section_name="slices",
            section_model=SlicePlan,
            system_prompt=system_slices,
            user_prompt=user_slices,
            project_id=project_id,
        )
    except Exception as exc:
        yield _sse({"error": f"Slice planning failed: {exc}", "done": True})
        return

    slices = slice_result.slices[:7]  # enforce max 7 at service boundary
    yield _sse({"step": "slices_planned", "count": len(slices)})

    # ------------------------------------------------------------------
    # Step 3 — Generate one UserStoryModel per slice
    # ------------------------------------------------------------------
    system_story = (
        "You are a senior product manager writing user stories. For the given slice:\n"
        "- title: short imperative title (e.g. 'Reset password via email')\n"
        "- description: must follow EXACTLY 'As a <persona>, I want <action>, so that <benefit>.'\n"
        "- acceptance_criteria: list covering happy path, at least one alternative path, "
        "and at least one error path. Each item is a complete sentence.\n"
        "- validations: list of field-level validation rules "
        "(field, rule, error_message). Include at least one row per form field implied by the slice.\n"
        "- priority: 'high' for must-have features (core user flow, blocking launch), "
        "'medium' for should-have (significant value, not launch-blocking), "
        "'low' for nice-to-have (enhancement, can defer). Base this on business impact from the PRD.\n"
        "- dependencies: list of OTHER story titles (from the same slice list) that must be "
        "completed before this story can begin. Use exact story titles. Empty list if none.\n"
        "- reference_links: list of documentation URLs or knowledge base references relevant "
        "to this story. Empty list if none."
    )

    # Collect all generated story models before diffing and persisting.
    # This allows classify_stories() to compare the full new set against existing rows.
    generated_story_models: list[UserStoryModel] = []

    for idx, slice_description in enumerate(slices):
        yield _HEARTBEAT

        user_story_prompt = (
            f"PRD CONTEXT:\n{prd_summary}\n\n"
            f"SLICE TO IMPLEMENT:\n{slice_description}\n\n"
            f"CAPABILITIES:\n{capabilities_text}\n\n"
            f"Write a complete user story for slice {idx + 1} of {len(slices)}."
        )

        try:
            story_model, _, _ = await generate_section(
                section_name=f"story_{idx + 1}",
                section_model=UserStoryModel,
                system_prompt=system_story,
                user_prompt=user_story_prompt,
                project_id=project_id,
            )
        except Exception as exc:
            yield _sse({"error": f"Story {idx + 1} generation failed: {exc}", "done": True})
            return

        generated_story_models.append(story_model)

    # ------------------------------------------------------------------
    # Diff new stories against existing rows (if any)
    # ------------------------------------------------------------------
    diff_result = classify_stories(
        existing=existing_stories or [],
        new_models=generated_story_models,
    )

    # ------------------------------------------------------------------
    # Persist diff results and stream story_done events
    # ------------------------------------------------------------------
    for entry in diff_result.entries:
        with Session(engine) as db:
            if entry.classification == "new":
                sm = entry.new_model
                story_row = UserStory(
                    project_id=project_id,
                    title=sm.title,
                    description=sm.description,
                    acceptance_criteria=json.dumps(sm.acceptance_criteria),
                    validations=json.dumps([v.model_dump() for v in sm.validations]),
                    priority=sm.priority,
                    dependencies=json.dumps(sm.dependencies),
                    reference_links=json.dumps(sm.reference_links),
                    story_status="open",
                )
                db.add(story_row)
                db.commit()
                db.refresh(story_row)
                story_id = story_row.id

            elif entry.classification == "modified":
                sm = entry.new_model
                existing_row = db.get(UserStory, entry.existing_id)
                if existing_row is not None:
                    existing_row.title = sm.title
                    existing_row.description = sm.description
                    existing_row.acceptance_criteria = json.dumps(sm.acceptance_criteria)
                    existing_row.validations = json.dumps([v.model_dump() for v in sm.validations])
                    existing_row.priority = sm.priority
                    existing_row.dependencies = json.dumps(sm.dependencies)
                    existing_row.reference_links = json.dumps(sm.reference_links)
                    db.add(existing_row)
                    db.commit()
                story_id = entry.existing_id

            elif entry.classification == "kept":
                story_id = entry.existing_id

            else:  # obsolete
                obsolete_row = db.get(UserStory, entry.existing_id)
                if obsolete_row is not None and obsolete_row.story_status != "done":
                    obsolete_row.story_status = "obsolete"
                    db.add(obsolete_row)
                    db.commit()
                # Emit a diff event (no story_done for obsolete)
                yield _sse({
                    "step": "story_diff",
                    "classification": "obsolete",
                    "story_id": entry.existing_id,
                    "title": entry.existing_title,
                })
                continue

        # Stream story_done event for new/modified/kept stories
        sm = entry.new_model
        yield _sse({
            "step": "story_done",
            "story": {
                "id": story_id,
                "title": sm.title,
                "description": sm.description,
                "acceptance_criteria": sm.acceptance_criteria,
                "validations": [v.model_dump() for v in sm.validations],
                "priority": sm.priority,
                "dependencies": sm.dependencies,
                "reference_links": sm.reference_links,
                "story_status": "open" if entry.classification in ("new", "modified") else "done",
            },
            "diff": entry.classification,
        })

    # ------------------------------------------------------------------
    # Advance workflow: PRD_APPROVED → STORIES_GENERATED
    # Re-generation from STORIES_GENERATED: already at the correct status.
    # advance_status is idempotent — calling it when already at STORIES_GENERATED
    # returns without error (it just detects it's already there).
    # ------------------------------------------------------------------
    advance_error: Optional[str] = None
    with Session(engine) as db:
        try:
            advance_status(project_id, WorkflowStatus.PRD_APPROVED, db)
        except HTTPException as exc:
            # 409 here means the status was not PRD_APPROVED — i.e. it was
            # STORIES_GENERATED (re-generation pass). That is expected and fine.
            if "STORIES_GENERATED" not in exc.detail:
                advance_error = exc.detail

    if advance_error is not None:
        yield _sse({"error": f"Workflow advance failed: {advance_error}", "done": True})
        return

    yield _sse({"done": True})


def _flatten_prd_for_prompts(prd_data: dict) -> str:
    """
    Convert the stored prd_data dict (with nested section dicts) into a
    compact plain text summary for use in story generation prompts.

    Each section dict is flattened to its key string fields, skipping
    internal metadata fields (source_doc_ids, type1_conflicts raw objects).
    """
    lines: list[str] = []

    section_order = ["title", "description", "problem", "why", "success", "audience", "open_questions"]
    for key in section_order:
        section = prd_data.get(key)
        if not section or not isinstance(section, dict):
            continue
        lines.append(f"\n## {key.upper()}")
        for field, value in section.items():
            if field == "source_doc_ids":
                continue
            if field == "type1_conflicts":
                # Flatten conflict entries to plain text
                if isinstance(value, list):
                    for conflict in value:
                        if isinstance(conflict, dict):
                            lines.append(
                                f"  [CONFLICT] {conflict.get('conflicting_statement', '')} → "
                                f"{conflict.get('proposed_change', '')} "
                                f"(severity: {conflict.get('severity', '')})"
                            )
                continue
            if isinstance(value, list):
                for item in value:
                    if isinstance(item, dict):
                        # GapEntry objects: show question text only
                        lines.append(f"  - {item.get('question', item)}")
                    else:
                        lines.append(f"  - {item}")
            elif value is not None:
                lines.append(f"  {field}: {value}")

    return "\n".join(lines)
