"""
Project-level routes mounted at /projects.

GET  /projects/{project_id}                        — rehydration endpoint for frontend
POST /projects/{project_id}/approve                — advance PRD_GENERATED → PRD_APPROVED
POST /projects/{project_id}/upload-refined-prd     — replace prd_json from uploaded .docx
                                                     + regenerate open_questions section
"""

from __future__ import annotations

import asyncio
import json
import time
from typing import Annotated, Optional

import structlog
from fastapi import APIRouter, Body, Depends, HTTPException, UploadFile, status
from sqlmodel import Session, select

from app.database import get_session
from app.models import Project
from app.services.ai import OpenQuestionsSection, generate_section
from app.services.docx_parser import parse_docx_by_headings
from app.services.rag import HybridRetriever
from app.services.vector_store import get_chroma_client, get_or_create_collection
from app.services.workflow import WorkflowStatus, advance_status

logger = structlog.get_logger()

router = APIRouter()

# ---------------------------------------------------------------------------
# Allowed statuses for refined-PRD upload
# ---------------------------------------------------------------------------
_REFINED_PRD_ALLOWED_STATUSES: frozenset[WorkflowStatus] = frozenset(
    {WorkflowStatus.PRD_GENERATED, WorkflowStatus.PRD_APPROVED}
)

# ---------------------------------------------------------------------------
# Section-key → prd_json field-dict converter
#
# parse_docx_by_headings() already returns snake_case keys via _match_section
# (e.g. "title", "description", "problem", "why", "success", "audience",
# "open_questions").  We only need to shape the flat text into the nested dict
# that prd_json stores for each section model.
# ---------------------------------------------------------------------------


def _build_section_dict(key: str, text: str) -> dict:
    """
    Convert a plain-text section body to the nested dict format stored in prd_json.

    The shape must match the corresponding Pydantic section model so that the
    frontend and story-generation prompts can deserialise it without errors.

    open_questions is intentionally excluded — it is always regenerated by AI.
    source_doc_ids is always empty on re-upload (no RAG assignment for static sections).
    """
    if key == "title":
        # TitleSection: {"title": str, "subtitle": None}
        # Heuristic: if the text contains " — ", treat the rest as subtitle.
        parts = text.split(" — ", 1)
        return {
            "title": parts[0].strip(),
            "subtitle": parts[1].strip() if len(parts) > 1 else None,
        }

    if key == "description":
        # DescriptionSection: {"overview": str, "source_doc_ids": []}
        return {"overview": text, "source_doc_ids": []}

    if key == "problem":
        # ProblemSection: {"problem_statement": str, "pain_points": [], "source_doc_ids": []}
        # Heuristic: lines starting with "- " or "• " are pain points.
        lines = text.splitlines()
        bullets: list[str] = []
        prose_lines: list[str] = []
        for line in lines:
            stripped = line.strip()
            if stripped.startswith("- ") or stripped.startswith("• "):
                bullets.append(stripped.lstrip("-• ").strip())
            else:
                prose_lines.append(stripped)
        return {
            "problem_statement": "\n".join(prose_lines).strip() or text,
            "pain_points": bullets,
            "source_doc_ids": [],
        }

    if key == "why":
        # WhySection: {"rationale": str, "business_value": str, "source_doc_ids": []}
        # Split at first blank line — first block = rationale, rest = business_value.
        paragraphs = [p.strip() for p in text.split("\n\n", 1) if p.strip()]
        return {
            "rationale": paragraphs[0] if paragraphs else text,
            "business_value": paragraphs[1] if len(paragraphs) > 1 else "",
            "source_doc_ids": [],
        }

    if key == "success":
        # SuccessSection: {"metrics": [], "kpis": [], "source_doc_ids": []}
        # Treat all bullet lines as metrics; no KPI inference from plain text.
        lines = text.splitlines()
        items = [l.strip().lstrip("-• ").strip() for l in lines if l.strip()]
        return {"metrics": items, "kpis": [], "source_doc_ids": []}

    if key == "audience":
        # AudienceSection: {"primary_audience": str, "secondary_audience": None,
        #                    "personas": [], "source_doc_ids": []}
        paragraphs = [p.strip() for p in text.split("\n\n", 1) if p.strip()]
        return {
            "primary_audience": paragraphs[0] if paragraphs else text,
            "secondary_audience": paragraphs[1] if len(paragraphs) > 1 else None,
            "personas": [],
            "source_doc_ids": [],
        }

    # Fallback for any unrecognised key: store as raw text under a "content" key.
    return {"content": text, "source_doc_ids": []}


@router.get("/{project_id}")
async def get_project(
    project_id: str,
    db: Annotated[Session, Depends(get_session)],
) -> dict:
    """Return a Project row as JSON for frontend rehydration."""
    statement = select(Project).where(Project.id == project_id)
    project: Optional[Project] = db.exec(statement).first()

    if project is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Project '{project_id}' not found.",
        )

    prd_parsed: Optional[dict] = None
    if project.prd_json:
        try:
            prd_parsed = json.loads(project.prd_json)
        except json.JSONDecodeError:
            prd_parsed = None

    qa_answers: dict = {}
    if project.qa_answers:
        try:
            qa_answers = json.loads(project.qa_answers)
        except json.JSONDecodeError:
            qa_answers = {}

    return {
        "id": project.id,
        "name": project.name,
        "created_by": project.created_by,
        "status": project.status.value,
        "transcript_text": project.transcript_text,
        "prd_json": prd_parsed,
        "qa_answers": qa_answers,
        "prompt_version": project.prompt_version,
        "generator_model": project.generator_model,
        "embedding_model": project.embedding_model,
        "extractor_model": project.extractor_model,
        "created_at": project.created_at.isoformat(),
    }


@router.post("/{project_id}/approve", status_code=status.HTTP_200_OK)
async def approve_prd(
    project_id: str,
    db: Annotated[Session, Depends(get_session)],
) -> dict:
    """Advance PRD_GENERATED → PRD_APPROVED."""
    updated_project = advance_status(
        project_id=project_id,
        expected_current=WorkflowStatus.PRD_GENERATED,
        db=db,
    )
    logger.info("projects.prd_approved", project_id=project_id)
    return {"status": updated_project.status.value, "project_id": project_id}


@router.post("/{project_id}/qa-answers", status_code=status.HTTP_200_OK)
async def save_qa_answers(
    project_id: str,
    db: Annotated[Session, Depends(get_session)],
    answers: Annotated[dict, Body(embed=False)],
) -> dict:
    """
    Persist user-provided answers to open questions / gaps / conflicts.

    Merges the incoming `answers` dict into any previously saved answers
    (new keys are added, existing keys are overwritten). Answers are stored
    as a JSON blob on Project.qa_answers for future PRD refinement (B3 loop).

    The endpoint is intentionally permissive about project status — answers
    can be saved at any point after a PRD has been generated.

    Request body: flat JSON object mapping question text → answer string.
    Response: { "project_id": str, "saved": int }
    """
    statement = select(Project).where(Project.id == project_id)
    project: Optional[Project] = db.exec(statement).first()

    if project is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Project '{project_id}' not found.",
        )

    # Merge with existing answers
    existing: dict = {}
    if project.qa_answers:
        try:
            existing = json.loads(project.qa_answers)
        except json.JSONDecodeError:
            existing = {}

    merged = {**existing, **answers}
    project.qa_answers = json.dumps(merged)
    db.add(project)
    db.commit()

    logger.info(
        "projects.qa_answers_saved",
        project_id=project_id,
        answer_count=len(merged),
    )
    return {"project_id": project_id, "saved": len(merged)}


# ---------------------------------------------------------------------------
# POST /projects/{project_id}/upload-refined-prd
# ---------------------------------------------------------------------------


@router.post("/{project_id}/upload-refined-prd", status_code=status.HTTP_200_OK)
async def upload_refined_prd(
    project_id: str,
    file: UploadFile,
    db: Annotated[Session, Depends(get_session)],
) -> dict:
    """
    Replace a project's prd_json with content from a user-refined .docx file,
    then regenerate the open_questions section against the current KB.

    Accepted file types: .docx only (422 for anything else).

    Allowed project statuses: PRD_GENERATED or PRD_APPROVED.
      - If PRD_APPROVED, the project is reset to PRD_GENERATED so the user can
        re-approve the updated PRD before generating stories.
      - STORIES_GENERATED and later states are rejected with 409 — a regenerate
        would silently invalidate already-generated stories or Jira tickets.

    The open_questions section is always regenerated (not taken from the DOCX)
    because it depends on the current KB state, not just the uploaded text.

    Returns
    -------
    {
        "project_id": str,
        "status": str,                  # project.status after write
        "open_questions": dict,         # model_dump() of OpenQuestionsSection
    }
    """
    # --- File type guard ---
    filename: str = file.filename or ""
    if not filename.lower().endswith(".docx"):
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Only .docx files are accepted for refined PRD upload.",
        )

    # --- Load project ---
    statement = select(Project).where(Project.id == project_id)
    project: Optional[Project] = db.exec(statement).first()

    if project is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Project '{project_id}' not found.",
        )

    if project.status not in _REFINED_PRD_ALLOWED_STATUSES:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=(
                f"Refined PRD upload requires project status PRD_GENERATED or PRD_APPROVED; "
                f"current status is '{project.status.value}'."
            ),
        )

    # --- Parse DOCX sections ---
    content: bytes = await file.read()
    try:
        prd_sections: dict[str, str] = parse_docx_by_headings(content)
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Failed to parse .docx file: {exc}",
        ) from exc

    if not prd_sections:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=(
                "The uploaded .docx contained no recognisable Heading 1 sections. "
                "Ensure the document uses Heading 1 style for all section titles."
            ),
        )

    # --- RAG retrieval for KB context (sync — offload to threadpool) ---
    start_ts = time.monotonic()
    chroma_client = get_chroma_client()
    collection = get_or_create_collection(chroma_client)
    retriever = HybridRetriever(collection, top_k=5)

    # Use the description section (truncated to 500 chars) as the retrieval query.
    # Fall back to title text, then to an empty string (returns [] from retriever).
    rag_query: str = (
        prd_sections.get("description", "")
        or prd_sections.get("title", "")
    )[:500]

    try:
        retrieved_nodes = await asyncio.to_thread(
            retriever.retrieve,
            rag_query,
            5,           # top_k positional arg
            project_id,  # project_id positional arg
        )
    except RuntimeError as exc:
        # KB unavailable — non-fatal; proceed without KB context.
        logger.warning(
            "projects.upload_refined_prd.rag_failed",
            project_id=project_id,
            error=str(exc),
        )
        retrieved_nodes = []

    # Build rag_context string for open_questions prompt injection
    rag_context_parts: list[str] = []
    for nws in retrieved_nodes:
        meta = nws.node.metadata
        doc_id = meta.get("doc_id", "unknown")
        section = meta.get("section", "")
        text = nws.node.get_content()
        rag_context_parts.append(f"[Source: {doc_id} / {section}]\n{text}")
    rag_context: str = (
        "\n\n---\n\n".join(rag_context_parts)
        if rag_context_parts
        else "(No prior knowledge base context.)"
    )

    rag_latency_ms = (time.monotonic() - start_ts) * 1000
    logger.info(
        "projects.upload_refined_prd.rag_complete",
        project_id=project_id,
        node_count=len(retrieved_nodes),
        latency_ms=round(rag_latency_ms, 2),
    )

    # --- Build full PRD text for open_questions prompt context ---
    # Exclude open_questions from the DOCX sections — it will be regenerated.
    sections_for_context: dict[str, str] = {
        k: v for k, v in prd_sections.items() if k != "open_questions"
    }
    prd_text_for_prompt = "\n\n".join(
        f"### {k.upper()}\n{v}" for k, v in sections_for_context.items() if v
    )

    # --- Regenerate open_questions via AI ---
    system_open_questions = (
        "You are a senior product manager writing a PRD. "
        "Your task is to write the OPEN QUESTIONS & RISKS section.\n\n"
        "This section has TWO required subsections — NEVER omit either:\n\n"
        "TYPE 1 — KB Conflicts (structured ConflictEntry objects):\n"
        "  Examine each knowledge base chunk provided. Identify direct contradictions between\n"
        "  what the transcript proposes and what existing PRDs state. For each conflict:\n"
        "    - source_prd_id: the doc_id from the KB chunk (e.g. 'payments-2024-01-15')\n"
        "    - conflicting_statement: quote the conflicting claim from the KB\n"
        "    - proposed_change: what the transcript proposes instead\n"
        "    - severity: 'blocking' | 'needs_discussion' | 'minor'\n"
        "    - kb_excerpt: copy verbatim the 1-3 sentences from the KB chunk that show the conflict.\n"
        "      Use the exact text from the [Source: ...] sections provided above.\n"
        "  If there are no conflicts, return an empty list — do NOT hallucinate conflicts.\n\n"
        "TYPE 2 — Transcript Gaps (GapEntry objects):\n"
        "  List questions about ambiguities, missing details, or decisions the PRD\n"
        "  left unresolved (e.g. scope boundaries, technical approach, compliance requirements).\n"
        "  For each gap:\n"
        "    - question: the gap as a clear, answerable question\n"
        "    - transcript_excerpt: copy 1-2 verbatim sentences from the PRD that prompted\n"
        "      this question. If the gap comes from complete absence of information, use an empty string.\n\n"
        "Ground every conflict in the KB context. Mark anything inferred as '(inferred)'."
    )
    user_open_questions = (
        f"PRD CONTENT (user-refined upload):\n{prd_text_for_prompt}\n\n"
        f"KNOWLEDGE BASE CONTEXT (prior PRDs — check these for Type 1 conflicts):\n{rag_context}\n\n"
        "Write the Open Questions & Risks section. Include both Type 1 conflicts and Type 2 gaps."
    )

    try:
        oq_result, _inp, _out = await generate_section(
            section_name="open_questions",
            section_model=OpenQuestionsSection,
            system_prompt=system_open_questions,
            user_prompt=user_open_questions,
            project_id=project_id,
        )
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Open questions generation failed: {exc}",
        ) from exc

    # --- Build new prd_json payload ---
    # Shape each parsed section into its stored nested dict format.
    new_prd_json: dict = {}
    for key, text in sections_for_context.items():
        new_prd_json[key] = _build_section_dict(key, text)

    # Always use the freshly generated open_questions (never from DOCX).
    new_prd_json["open_questions"] = oq_result.model_dump()

    # --- Persist to DB + reset status if needed ---
    was_approved: bool = project.status == WorkflowStatus.PRD_APPROVED
    project.prd_json = json.dumps(new_prd_json)

    if was_approved:
        # Reset to PRD_GENERATED so user must re-approve the refined PRD
        # before stories can be generated.
        project.status = WorkflowStatus.PRD_GENERATED

    db.add(project)
    db.commit()
    db.refresh(project)

    logger.info(
        "projects.upload_refined_prd.complete",
        project_id=project_id,
        sections_parsed=list(prd_sections.keys()),
        was_approved=was_approved,
        new_status=project.status.value,
        type1_conflicts=len(oq_result.type1_conflicts),
        type2_gaps=len(oq_result.type2_gaps),
    )

    return {
        "project_id": project_id,
        "status": project.status.value,
        "open_questions": oq_result.model_dump(),
    }
